### ISSUE TITLE
neural network with mnist

### ISSUE THREAD

**Issue by ykocaturk** [brian-j-smith/MachineShop#8]
Hi,
The model gives an error in the neural network operation of the mnist data. Could the model not work in the multi-factor target variable?
thanks.

**Comment by brian-j-smith** [comment]
`NNetModel` can be used with target variables that have been coded as a factor (2 or more levels) in the data being analyzed.  Coding of factor target/response variables is described in the [user guide](https://brian-j-smith.github.io/MachineShop/using.html#Factor) and further illustrated in the [Iris example](https://brian-j-smith.github.io/MachineShop/example_iris.html).

If you are still having the issue after following the documentation links, then we would need the precise error message and a minimal example that can be run by others to help diagnose and resolve the error.
